include: package:lint/analysis_options.yaml

analyzer:
  errors:
    argument_type_not_assignable: false
    invalid_assignment: false
    return_of_invalid_type: false
    invalid_annotation_target: ignore
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - lib/core/di/di.config.dart