name: swapi
description: SWAPI test
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  lint: ^2.1.2
  injectable: ^2.1.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  get_it: ^7.6.0
  json_annotation: ^4.8.1
  dio: ^5.2.1+1
  flutter_bloc: ^8.1.3
  fast_immutable_collections: ^9.1.5
  animated_theme_switcher: ^2.0.8
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  injectable_generator: ^2.1.6

flutter:
  generate: true
  uses-material-design: true

